version: '3'

services: 

    frontend:
        image: example-frontend
        build: .
        ports:
            - 5000:5000
        container_name: frontend
    
    backend:
        image: example-backend
        build: .
        ports:
            - 8080:8080
        container_name: backend
    

