version: '3'

services: 

    frontend:
        image: example-frontend
        build: .
        ports:
            - 5000:5000
        container_name: frontend
    
    backend:
        image: example-backend
        build: .
        ports:
            - 8080:8080
        environment:
            - REDIS_HOST=redis
            - POSTGRES_HOST=db
        depends_on: 
            - db
            - redis
        container_name: backend
    
    redis:
        image: redis:alpine
        ports:
            - 6379:6379

    db:
        image: postgres:13.2-alpine
        restart: unless-stopped
        environment: 
            POSTGRES_PASSWORD: postgres
        container_name: db_backend



