version: '3'

services: 

    frontend:
        image: example-frontend
        container_name: frontend
        networks:
            - proxy-network
    
    backend:
        image: example-backend
        environment:
            - REDIS_HOST=redis
            - POSTGRES_HOST=db
        depends_on: 
            - db
            - redis
        container_name: backend
        networks:
            - proxy-network
            - db-network
    
    redis:
        image: redis:alpine
        ports:
            - 6379:6379
        networks:
            - db-network
        container_name: redis
        volumes: 
            - ./database_redis:/data
    
    reverse-proxy:
        image: nginx:stable-alpine
        volumes: 
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - 80:80
        networks:
            - proxy-network
        container_name: proxy
        depends_on: 
            - frontend
            - backend

    db:
        image: postgres:13.2-alpine
        restart: unless-stopped
        environment: 
            POSTGRES_PASSWORD: postgres
        container_name: db_backend
        volumes: 
            - ./database:/var/lib/postgresql/data
        networks:
            - db-network

networks: 
    proxy-network:
        name: proxy-network
    db-network:
        name: db-network

volumes: 
    database:
    database_redis:
    





